name: Deploy to EKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      
      - name: Deploy to EKS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EKS_CLUSTER_HOST }}
          username: ${{ secrets.EKS_CLUSTER_USERNAME }}
          key: ${{ secrets.EKS_CLUSTER_SSH_KEY }}
          script: kubectl apply -f ./kubernetes-manifests/

